<template>
    <div class="main-container">
        <h1>Indiquez le modèle de votre véhicule</h1>
        <div class="main-content">
            <div class="subcategory-grid">
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A1
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A2
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A3
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A4
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A4 Allroad
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A5
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A6 Allroad
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A7
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    A8
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    Q2
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    Q3
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    Q5
                </NuxtLink>
                <NuxtLink
                    :to="`/vehicleInfos/circulationDate`"
                    class="subcategory-item"
                >
                    Q7
                </NuxtLink>
            </div>
        </div>
    </div>
</template>
